### PR TITLE
Visual Basic Security Hotspots rules should only be displayed on SonarQube/SonarCloud

### LINKED ISSUE #2091: Security Hotspot rules not disabled on SonarQube 6.7
### Description

As expected, Security Hotspot rules are disabled in sonar-csharp for SonarQube 6.7.
However they are enabled and part of Sonar Way for VB.Net

### Repro steps

Just install the SonarVBNet plugin in SonarQube.
The result is visible on Peach on the rules page: https://peach.sonarsource.com/coding_rules#available_since=2018-11-01

### Expected behavior

The VB.Net Hotspot rules should behave the same way as the C# ones on SonarQube 6.7, i.e. be completely disabled. Hotspot rules are disabled on SonarQube 6.7 so that they don't pollute the "Sonar Way" quality profile as a Vulnerability rule (Security Hotspot type doesn't exist in SonarQube 6.7).

### Related information

* SonarC# and SonarVBNet 7.9.0.7458 built from the Pull request Feature/hotspots
* SonarQube Version 6.7.3 (build 38325) (Peach)

### PR DESCRIPTION
**Pull request by valhristov**
Fix #2091

### CODE REVIEW

File: sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpSonarWayProfile.java [hunk 1]
```diff
@@ -25,37 +25,27 @@
...
-  private final boolean supportsSecurityHotspots;
-  private static final Version SQ_7_3 = Version.create(7, 3);
 
   CSharpSonarWayProfile(@Nullable SonarRuntime sonarRuntime) {
-    this.supportsSecurityHotspots = sonarRuntime != null && sonarRuntime.getApiVersion().isGreaterThanOrEqual(SQ_7_3);
+    super(sonarRuntime, CSharpPlugin.LANGUAGE_KEY, CSharpPlugin.PLUGIN_KEY, CSharpPlugin.REPOSITORY_KEY);
   }
 
   @Override
-  public void define(Context context) {
```
Comment (valhristov) [inline sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpSonarWayProfile.java]: Extracted the common code that determines which sonar way profile definition to load depending on the SQ version

File: sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpSonarWayProfile.java [hunk 2]
```diff
@@ -25,37 +25,27 @@
...
-    NewBuiltInQualityProfile sonarWay = context.createBuiltInQualityProfile("Sonar way", CSharpPlugin.LANGUAGE_KEY);
-    String sonarWayJsonPath = supportsSecurityHotspots
-      ? "org/sonar/plugins/csharp/Sonar_way_profile.json"
-      : "org/sonar/plugins/csharp/Sonar_way_profile_no_hotspot.json";
-    BuiltInQualityProfileJsonLoader.load(sonarWay, CSharpPlugin.REPOSITORY_KEY, sonarWayJsonPath);
-    final String repositoryKey = getRepositoryKey();
+  protected void activateSecurityRules(NewBuiltInQualityProfile sonarWay) {
```
Comment (valhristov) [inline sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpSonarWayProfile.java]: The security rules are still C#-only

File: sonar-vbnet-plugin/src/main/java/org/sonar/plugins/vbnet/VbNetPlugin.java [hunk 3]
```diff
@@ -62,6 +61,7 @@ public void define(Context context) {
       RoslynProfileExporter.class);
 
     context.addExtensions(new VbNetPropertyDefinitions(context.getRuntime()).create());
+    context.addExtension(new VbNetSonarWayProfile(context.getRuntime()));
```
Comment (valhristov) [inline sonar-vbnet-plugin/src/main/java/org/sonar/plugins/vbnet/VbNetPlugin.java]: There is no default ctor on the class now and we need to register the instance through a different method

File: sonar-vbnet-plugin/src/test/java/org/sonar/plugins/vbnet/VbNetPluginTest.java [hunk 4]
```diff
@@ -70,6 +69,7 @@ public void getExtensions() {
 
     assertThat(extensions).hasSize(
       expectedExtensions.length
+        + 1 // VbNetSonarWayProfile
```
Comment (valhristov) [inline sonar-vbnet-plugin/src/test/java/org/sonar/plugins/vbnet/VbNetPluginTest.java]: it is only one extension (the singleton instance)

**Comment by valhristov** [comment]
@duncanp-sonar 	you could use the following command to add the missing headers `mvn license:format`

I copied the license header from a C# file, the difference was C# vs VB and the year... Spent some time to look what's wrong before I remembered there is a command for that :)
