### PR TITLE
Dm/refactor

### LINKED ISSUE #917: Remove support for deprecated 'sonar.cs.msbuild.testProjectPattern'
### Description
The server property 'sonar.cs.msbuild.testProjectPattern' has been replaced by the client-side property ''sonar.msbuild.testProjectPattern'. It's time to remove it.

### Related information
https://jira.sonarsource.com/browse/SONARMSBRU-345

### LINKED ISSUE #934: Don't fail to parse issues on file names with '['
### Description

The plugin fails to parse Roslyn issue reports that refer to file names containing "[" or "]".

### Repro steps

1. Create the file "Program[1].cs"
2. Analyze a project containing the file

### Expected behavior

Issues in the file are imported from the roslyn report.

### Actual behavior

Exception:
`ERROR: Error during SonarQube Scanner execution
java.lang.IllegalArgumentException: Illegal character in path at index 91: file:///C:/ConsoleApplication1/Program[1].cs
        at java.net.URI.create(URI.java:852)
        at org.sonarsource.dotnet.shared.sarif.SarifParser10.uriToAbsolutePath(SarifParser10.java:188)
        at org.sonarsource.dotnet.shared.sarif.SarifParser10.handleLocation(SarifParser10.java:139)
        at org.sonarsource.dotnet.shared.sarif.SarifParser10.handleResultFileElement(SarifParser10.java:110)
        at org.sonarsource.dotnet.shared.sarif.SarifParser10.handleLocationsElement(SarifParser10.java:102)
        at org.sonarsource.dotnet.shared.sarif.SarifParser10.handleIssue(SarifParser10.java:73)
        at org.sonarsource.dotnet.shared.sarif.SarifParser10.handleIssues(SarifParser10.java:62)
        at org.sonarsource.dotnet.shared.sarif.SarifParser10.accept(SarifParser10.java:54)
        at org.sonarsource.dotnet.shared.sarif.SarifParser10.accept(SarifParser10.java:37)
        at org.sonar.plugins.csharp.CSharpSensor.importRoslynReport(CSharpSensor.java:125)
        at org.sonar.plugins.csharp.CSharpSensor.executeInternal(CSharpSensor.java:102)
        at org.sonar.plugins.csharp.CSharpSensor.execute(CSharpSensor.java:69)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:281)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
        at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.net.URISyntaxException: Illegal character in path at index 91: file:///C:/ConsoleApplication1/Program[1].cs
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3105)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at java.net.URI.create(URI.java:850)`

File path is edited, so index doesn't match.

### PR DESCRIPTION
**Pull request by dbmeneses**
Fix #934, Fix #917

### CODE REVIEW

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/ProtobufDataImporter.java [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+
+  private final FileLinesContextFactory fileLinesContextFactory;
+  private final NoSonarFilter noSonarFilter;
+
+  public ProtobufDataImporter(FileLinesContextFactory fileLinesContextFactory, NoSonarFilter noSonarFilter) {
+    this.fileLinesContextFactory = fileLinesContextFactory;
+    this.noSonarFilter = noSonarFilter;
+  }
+
+  public void importResults(SensorContext context, Path protobufReportsDirectory, String repositoryKey, boolean importIssues) {
```
Comment (SonarTech) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/ProtobufDataImporter.java]: MAJOR Provide multiple methods instead of using "importIssues" to determine which action to take. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS2301)

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractConfiguration.java [hunk 2]
```diff
@@ -19,67 +19,75 @@
...
-      return count != 0;
+      return true;
     } catch (IOException e) {
-      LOG.warn("Could not check for .pb files in " + analyzerOutputDir.toAbsolutePath().toString(), e);
+      throw new IllegalStateException("Could not check for .pb files in " + analyzerOutputDir.toAbsolutePath(), e);
+    }
+  }
+
+  public boolean isRoslynReportPresent() {
+    if (!settings.hasKey(getRoslynJsonReportPathProperty())) {
```
Comment (SonarTech) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractConfiguration.java]: MINOR Replace this if-then-else statement by a single return statement. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS1126)

File: sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpSensor.java [hunk 3]
```diff
@@ -21,45 +21,41 @@
...
   private final CSharpConfiguration config;
   private final System2 system;
+  private final ProtobufDataImporter protobufDataImporter;
+  private final RoslynDataImporter roslynDataImporter;
 
-  public CSharpSensor(Settings settings, FileLinesContextFactory fileLinesContextFactory,
-    NoSonarFilter noSonarFilter, CSharpConfiguration config, EncodingPerFile encodingPerFile, System2 system) {
-    super(fileLinesContextFactory, noSonarFilter, config, encodingPerFile, CSharpSonarRulesDefinition.REPOSITORY_KEY);
-    this.settings = settings;
+  public CSharpSensor(FileLinesContextFactory fileLinesContextFactory, NoSonarFilter noSonarFilter, CSharpConfiguration config,
```
Comment (SonarTech) [inline sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpSensor.java]: MAJOR Remove these unused method parameters. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS1172)

**Comment by SonarTech** [comment]
SonarQube analysis reported 3 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by dbmeneses** [comment]
@Evangelink yes, it's ok

File: sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpMsBuildIntegrationProvider.java [hunk 4]
```diff
@@ -1,49 +0,0 @@
...
-public class CSharpMsBuildIntegrationProvider {
-
-  private static final String CATEGORY = "Scanner for MSBuild";
-
-  private CSharpMsBuildIntegrationProvider() {
-  }
-
-  public static List extensions() {
-    return Collections.singletonList(
-      PropertyDefinition.builder("sonar.cs.msbuild.testProjectPattern")
```
Comment (michalb-sonar) [inline sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpMsBuildIntegrationProvider.java]: If the users try to use this property, would they get an error message that property doesn't exist, or a silent failure (I presume the former)?

Comment (dbmeneses) [reply sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpMsBuildIntegrationProvider.java]: They can't use the property, as it won't appear anymore in the settings in the server.

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SarifParserCallbackImpl.java [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+    newIssue
+      .forRule(RuleKey.of(repositoryKey, ruleId))
+      .at(newIssue.newLocation()
+        .on(inputFile)
+        .at(inputFile.newRange(primaryLocation.getStartLine(), primaryLocation.getStartColumn(),
+          primaryLocation.getEndLine(), primaryLocation.getEndColumn()))
+        .message(primaryLocation.getMessage()));
+
+    for (Location secondaryLocation : secondaryLocations) {
+      if (!inputFile.absolutePath().equalsIgnoreCase(secondaryLocation.getAbsolutePath())) {
```
Comment (SonarTech) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SarifParserCallbackImpl.java]: MINOR Remove this use of "absolutePath"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/ProtobufDataImporter.java (hunk 1 above)
Comment (SonarTech) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/ProtobufDataImporter.java]: MAJOR Provide multiple methods instead of using "importIssues" to determine which action to take. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS2301)

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractConfiguration.java [hunk 6]
```diff
@@ -19,68 +19,73 @@
...
   }
 
-  public Path protobufReportPathFromScanner() {
-    String analyzerWorkDirPath = settings.getString(getAnalyzerWorkDirProperty());
+  public boolean isRoslynReportPresent() {
+    return configuration.hasKey(getRoslynJsonReportPathProperty());
+  }
+
+  public Path roslynReportPath() {
+    return Paths.get(configuration.get(getRoslynJsonReportPathProperty()).get());
```
Comment (SonarTech) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractConfiguration.java]: MAJOR Call "Optional#isPresent()" before accessing the value. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS3655)

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractConfiguration.java [hunk 7]
```diff
@@ -19,68 +19,73 @@
...
+  }
+
+  /**
+   * Returns path of the directory containing all protobuf files.
+   * Check if it exists with {@link AbstractConfiguration#areProtobufReportsPresent()}.
+   */
+  public Path protobufReportPath() {
+    String analyzerWorkDirPath = configuration.get(getAnalyzerWorkDirProperty()).get();
```
Comment (SonarTech) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractConfiguration.java]: MAJOR Call "Optional#isPresent()" before accessing the value. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS3655)

**Comment by SonarTech** [comment]
SonarQube analysis reported 10 issues
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 7 minor

Watch the comments in this conversation to review them.

#### 6 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [GeneratedFileFilter.java#L57](https://github.com/SonarSource/sonar-csharp/blob/149e5124fd5ff6f711fb4a7c94ba232516b33b94/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/GeneratedFileFilter.java#L57): Remove this use of "path"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [GeneratedFileFilter.java#L59](https://github.com/SonarSource/sonar-csharp/blob/149e5124fd5ff6f711fb4a7c94ba232516b33b94/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/GeneratedFileFilter.java#L59): Remove this use of "path"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [MetricsImporter.java#L58](https://github.com/SonarSource/sonar-csharp/blob/149e5124fd5ff6f711fb4a7c94ba232516b33b94/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java#L58): Remove this use of "FILE_COMPLEXITY_DISTRIBUTION"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [MetricsImporter.java#L59](https://github.com/SonarSource/sonar-csharp/blob/149e5124fd5ff6f711fb4a7c94ba232516b33b94/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java#L59): Remove this use of "FUNCTION_COMPLEXITY_DISTRIBUTION"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [MetricsImporter.java#L60](https://github.com/SonarSource/sonar-csharp/blob/149e5124fd5ff6f711fb4a7c94ba232516b33b94/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java#L60): Remove this use of "COMPLEXITY_IN_CLASSES"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [MetricsImporter.java#L61](https://github.com/SonarSource/sonar-csharp/blob/149e5124fd5ff6f711fb4a7c94ba232516b33b94/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java#L61): Remove this use of "COMPLEXITY_IN_FUNCTIONS"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/EncodingPerFile.java [hunk 8]
```diff
@@ -22,53 +22,39 @@
...
-
-  void init(Path reportDir) {
-    EncodingImporter encodingImporter = getEncodingImporter();
-
-    Path encodingReportProtobuf = reportDir.resolve(ENCODING_OUTPUT_PROTOBUF_NAME);
-    if (encodingReportProtobuf.toFile().exists()) {
-      encodingImporter.accept(encodingReportProtobuf);
-    } else {
-      LOG.warn("Protobuf file not found: {}", encodingReportProtobuf);
+  void init(Optional<Path> protobufDir) {
```
Comment (SonarTech) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/EncodingPerFile.java]: MINOR Specify a "Path" parameter instead. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS3553)

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SarifParserCallbackImpl.java (hunk 5 above)
Comment (SonarTech) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SarifParserCallbackImpl.java]: MINOR Remove this use of "absolutePath"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/ProtobufDataImporter.java (hunk 1 above)
Comment (SonarTech) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/ProtobufDataImporter.java]: MAJOR Provide multiple methods instead of using "importIssues" to determine which action to take. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS2301)

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractConfiguration.java [hunk 9]
```diff
@@ -19,69 +19,72 @@
...
-      return false;
+      throw new IllegalStateException("Could not check for .pb files in " + analyzerOutputDir.toAbsolutePath(), e);
     }
   }
 
-  public Path protobufReportPathFromScanner() {
-    String analyzerWorkDirPath = settings.getString(getAnalyzerWorkDirProperty());
-    return Paths.get(analyzerWorkDirPath, getAnalyzerReportDir());
+  public Optional<Path> roslynReportPath() {
+    return configuration.get(getRoslynJsonReportPathProperty()).map(p -> Paths.get(p));
```
Comment (SonarTech) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractConfiguration.java]: MINOR Replace this lambda with a method reference. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS1612)

File: sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpPlugin.java [hunk 10]
```diff
@@ -24,11 +24,14 @@
...
 import org.sonar.api.PropertyType;
 import org.sonarsource.dotnet.shared.plugins.EncodingPerFile;
-import org.sonarsource.dotnet.shared.plugins.WrongEncodingFileFilter;
 import org.sonarsource.dotnet.shared.plugins.GeneratedFileFilter;
+import org.sonarsource.dotnet.shared.plugins.ProtobufDataImporter;
+import org.sonarsource.dotnet.shared.plugins.RoslynDataImporter;
+import org.sonarsource.dotnet.shared.plugins.WrongEncodingFileFilter;
 
 @Properties({
   @Property(
```
Comment (SonarTech) [inline sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpPlugin.java]: MINOR Reorder annotation arguments to match the order of declaration. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS3340)

**Comment by SonarTech** [comment]
SonarQube analysis reported 11 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 10 minor

Watch the comments in this conversation to review them.

#### 6 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [GeneratedFileFilter.java#L57](https://github.com/SonarSource/sonar-csharp/blob/17b94f2806279b57b22aa3024001b2f7796e3fa6/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/GeneratedFileFilter.java#L57): Remove this use of "path"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [GeneratedFileFilter.java#L59](https://github.com/SonarSource/sonar-csharp/blob/17b94f2806279b57b22aa3024001b2f7796e3fa6/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/GeneratedFileFilter.java#L59): Remove this use of "path"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [MetricsImporter.java#L58](https://github.com/SonarSource/sonar-csharp/blob/17b94f2806279b57b22aa3024001b2f7796e3fa6/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java#L58): Remove this use of "FILE_COMPLEXITY_DISTRIBUTION"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [MetricsImporter.java#L59](https://github.com/SonarSource/sonar-csharp/blob/17b94f2806279b57b22aa3024001b2f7796e3fa6/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java#L59): Remove this use of "FUNCTION_COMPLEXITY_DISTRIBUTION"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [MetricsImporter.java#L60](https://github.com/SonarSource/sonar-csharp/blob/17b94f2806279b57b22aa3024001b2f7796e3fa6/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java#L60): Remove this use of "COMPLEXITY_IN_CLASSES"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [MetricsImporter.java#L61](https://github.com/SonarSource/sonar-csharp/blob/17b94f2806279b57b22aa3024001b2f7796e3fa6/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java#L61): Remove this use of "COMPLEXITY_IN_FUNCTIONS"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/EncodingPerFile.java (hunk 8 above)
Comment (SonarTech) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/EncodingPerFile.java]: MINOR Specify a "Path" parameter instead. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS3553)

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SarifParserCallbackImpl.java (hunk 5 above)
Comment (SonarTech) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SarifParserCallbackImpl.java]: MINOR Remove this use of "absolutePath"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/ProtobufDataImporter.java (hunk 1 above)
Comment (SonarTech) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/ProtobufDataImporter.java]: MAJOR Provide multiple methods instead of using "importIssues" to determine which action to take. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS2301)

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractConfiguration.java (hunk 9 above)
Comment (SonarTech) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/AbstractConfiguration.java]: MINOR Replace this lambda with a method reference. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS1612)

**Comment by SonarTech** [comment]
SonarQube analysis reported 10 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 9 minor

Watch the comments in this conversation to review them.

#### 6 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [GeneratedFileFilter.java#L57](https://github.com/SonarSource/sonar-csharp/blob/4021efa52de218e2b842802383a47ae9e44f2041/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/GeneratedFileFilter.java#L57): Remove this use of "path"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [GeneratedFileFilter.java#L59](https://github.com/SonarSource/sonar-csharp/blob/4021efa52de218e2b842802383a47ae9e44f2041/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/GeneratedFileFilter.java#L59): Remove this use of "path"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [MetricsImporter.java#L58](https://github.com/SonarSource/sonar-csharp/blob/4021efa52de218e2b842802383a47ae9e44f2041/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java#L58): Remove this use of "FILE_COMPLEXITY_DISTRIBUTION"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [MetricsImporter.java#L59](https://github.com/SonarSource/sonar-csharp/blob/4021efa52de218e2b842802383a47ae9e44f2041/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java#L59): Remove this use of "FUNCTION_COMPLEXITY_DISTRIBUTION"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [MetricsImporter.java#L60](https://github.com/SonarSource/sonar-csharp/blob/4021efa52de218e2b842802383a47ae9e44f2041/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java#L60): Remove this use of "COMPLEXITY_IN_CLASSES"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [MetricsImporter.java#L61](https://github.com/SonarSource/sonar-csharp/blob/4021efa52de218e2b842802383a47ae9e44f2041/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java#L61): Remove this use of "COMPLEXITY_IN_FUNCTIONS"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/EncodingPerFile.java (hunk 8 above)
Comment (SonarTech) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/EncodingPerFile.java]: MINOR Specify a "Path" parameter instead. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS3553)

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SarifParserCallbackImpl.java (hunk 5 above)
Comment (SonarTech) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/SarifParserCallbackImpl.java]: MINOR Remove this use of "absolutePath"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/ProtobufDataImporter.java (hunk 1 above)
Comment (SonarTech) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/ProtobufDataImporter.java]: MAJOR Provide multiple methods instead of using "importIssues" to determine which action to take. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3AS2301)

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/GeneratedFileFilter.java [hunk 11]
```diff
@@ -56,7 +56,7 @@ public boolean accept(InputFile inputFile) {
 
     boolean isGenerated = generatedFilePaths.contains(inputFile.path());
```
Comment (SonarTech) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/GeneratedFileFilter.java]: MINOR Remove this use of "path"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

**Comment by SonarTech** [comment]
SonarQube analysis reported 8 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 7 minor

Watch the comments in this conversation to review them.

#### 4 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [MetricsImporter.java#L58](https://github.com/SonarSource/sonar-csharp/blob/d349549d324b20e519c2062d6fb860c008f7f556/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java#L58): Remove this use of "FILE_COMPLEXITY_DISTRIBUTION"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [MetricsImporter.java#L59](https://github.com/SonarSource/sonar-csharp/blob/d349549d324b20e519c2062d6fb860c008f7f556/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java#L59): Remove this use of "FUNCTION_COMPLEXITY_DISTRIBUTION"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [MetricsImporter.java#L60](https://github.com/SonarSource/sonar-csharp/blob/d349549d324b20e519c2062d6fb860c008f7f556/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java#L60): Remove this use of "COMPLEXITY_IN_CLASSES"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
1. ![MINOR][MINOR] [MetricsImporter.java#L61](https://github.com/SonarSource/sonar-csharp/blob/d349549d324b20e519c2062d6fb860c008f7f556/sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/plugins/protobuf/MetricsImporter.java#L61): Remove this use of "COMPLEXITY_IN_FUNCTIONS"; it is deprecated. [rule](https://next.sonarqube.com/sonarqube/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParser10.java [hunk 12]
```diff
@@ -185,7 +185,8 @@ private static boolean isSuppressed(JsonObject resultObj) {
   }
 
   private static String uriToAbsolutePath(String uri) {
-    return new File(URI.create(uri)).getAbsolutePath();
+    String uriEscaped = uri.replace("[", "%5B").replace("]", "%5D");
```
Comment (henryju) [inline sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParser10.java]: Shouldn't it be reported as a bug to Microsoft?

Comment (dbmeneses) [reply sonar-dotnet-shared-library/src/main/java/org/sonarsource/dotnet/shared/sarif/SarifParser10.java]: We'll look into it
