### PR TITLE
Fail analysis when OS is not Windows

### LINKED ISSUE #535: CSharp sensor should fail if OS is not windows.
### Description

If a build server accidentally pushes a csharp analysis to a non-windows system, the c# files are ignored in analysis (without warning) and sonar history deletes them. It's not possible to delete the latest analysis in Sonar, so this is breaking the history until rescan on Windows has happened.

When running in debug mode, there is a warning about OS Incompatibility.

### Repro steps

1. Scan C# project on Mac or Linux.

### Expected behavior

Sonar C# should either:
- scan C# as good as possible
- fail and stop the analysis.

### Actual behavior

- Silently goes forward while only logging in debug mode.
- Resets C# analysis on SonarQube server

### Known workarounds

- Dont' run on non-windows.

### PR DESCRIPTION
**Pull request by valhristov**
Fix #535

### CODE REVIEW

File: sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpSensor.java [hunk 1]
```diff
@@ -70,17 +74,17 @@ public void execute(SensorContext context) {
...
-      return false;
-    }
-
+  private boolean shouldExecuteOnProject(FileSystem fs) {
     if (!filesToAnalyze(fs).iterator().hasNext()) {
       LOG.debug("No files to analyze. Skip Sensor.");
       return false;
     }
 
+    if (!system.isOsWindows()) {
```
Comment (valhristov) [inline sonar-csharp-plugin/src/main/java/org/sonar/plugins/csharp/CSharpSensor.java]: We are checking the OS after we check if there are files to analyze in order to allow the user to disable the SonarC# plugin when they are analyzing on non-Windows OS projects that contain C# files (for some reason)
