### PR TITLE
Do not skip source files that contains ExcludeFromCodeCoverage* attributes

### LINKED ISSUE #428: Do not skip source files that contains "ExcludeFromCodeCoverage*" attributes
### Description

If a source file contains "ExcludeFromCodeCoverage" or "ExcludeFromCodeCoverageAttribute" code attribute, the analyzer will skip the file from the analysis.

This mechanism has been put in place the prevent SonarC# to analyze generated source code. This codding attributes are not related to auto-generated code. 

The aim of this issue to prevent the analyzer to skip any source file relying on these coding attributes.
[Here](https://github.com/SonarSource/sonaranalyzer-dotnet/blob/master/src/SonarAnalyzer.Common/Helpers/GeneratedCodeRecognizer.cs#L56,L57) is the related source code.

### Repro steps

 - create a project
 - 2 source files of this project respectively uses code attribute  "ExcludeFromCodeCoverage" or "ExcludeFromCodeCoverageAttribute"
 - run the analysis
 - confirm that the files are skipped

### Related information
It impact any analysis since version 5.4 of SonarC#.

### PR DESCRIPTION
**Pull request by michalb-sonar**
Fix #428

### CODE REVIEW

**Comment by michalb-sonar** [comment]
@Evangelink I've added tests as you suggested, please re-review
FYI @valhristov

File: its/src/test/java/com/sonar/it/csharp/Tests.java [hunk 1]
```diff
@@ -56,7 +56,7 @@
   DoNotAnalyzeTestFilesTest.class,
   MetricsTest.class,
   NoSonarTest.class,
-  UnitTestResultsTest.class
```
Comment (Evangelink) [inline its/src/test/java/com/sonar/it/csharp/Tests.java]: Is it normal to have removed one test class?

Comment (michalb-sonar) [reply its/src/test/java/com/sonar/it/csharp/Tests.java]: Good catch, thanks!
